### PR TITLE
Add pull request template

### PR DESCRIPTION
**Pull request by remi**
## 📖 Description

The project didn’t have a pull request template so I added one from one of our other boilerplate projects, [elixir-boilerplate](https://github.com/mirego/elixir-boilerplate).

I didn’t use the same one from the other Trikot repositories ([example](https://github.com/mirego/trikot.viewmodels/blob/master/.github/pull_request_template.md)) since this repository is a boilerplate project and a not a library.

### CODE REVIEW

**Comment by marcantoinefortier** [comment]
We used a [different template](https://github.com/mirego/trikot.streams/blob/master/.github/pull_request_template.md) on trikot.streams. Do you think we should use the same on all ou libs? 

While this is not actually a lib (it's a template), I think we could work to make them look as similar as possible.

**Comment by remi** [comment]
> We used a different template on trikot.streams. Do you think we should use the same on all our libs?

Yes, probably 🙂

> While this is not actually a lib (it's a boilerplate like you said), I think we could work to make them look as similar as possible.

I think what you suggest is another task because of its broader scope. I say we merge this template for now, then we take a look at _all of our open-source projects_ (https://open.mirego.com) and try to come up with a “standard” template in the future. What do you think?

**Review by Boubalou — APPROVED** [review]
I like having a preformatted table for before and after, which also add a moment of "Damn, right, I should add a screenshot of my work" when they are about to remove the section :)

```
## 🎉 Results

<!-- Any work worth presenting that might be helpful to reviewers? -->

| Before         | After         |
| -------------- | ------------- |
| _before_image_ | _after_image_ |
```

**Comment by remi** [comment]
> I like having a preformatted table for before and after,

Yes, absolutely! I’ll start a thread in our internal development channel so we can pitch ideas for improvements.

**Pull request merged**
